"""Platform application services.

This package intentionally uses lazy exports. `models.py` re-exports the
platform model-settings contract during the DDD migration, and eager imports
from this package would otherwise create a circular dependency through account
and tool services that still consume compatibility DTOs from `models.py`.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "AccountApplicationService",
    "AccountIdentityPort",
    "AuthLoginRequest",
    "AuthRegisterRequest",
    "AuthSessionResponse",
    "AuditEvent",
    "AuditEventPersistencePort",
    "AuthServiceError",
    "AuthSessionResult",
    "AvatarImageContent",
    "BuildResponse",
    "CurrentUserProviderPort",
    "DashboardResponse",
    "DemoSeedApplicationService",
    "DemoSeedBaseline",
    "DemoSeedSystemImage",
    "DemoSeedWorkspacePort",
    "DocumentationEntry",
    "product_documentation_entries",
    "GovernanceApplicationError",
    "GovernanceApplicationService",
    "ModelConfigurationApplicationService",
    "ModelConfigurationGatewayPort",
    "ModelConfigurationRepositoryPort",
    "ModelConfigurationSecretPort",
    "ModelConfigurationStatePort",
    "ModelConfigurationTestGrantPort",
    "OperationalMetricsExportPort",
    "PlatformApplicationError",
    "PlatformAuditApplicationService",
    "PlatformEventApplicationService",
    "PlatformEventStreamApplicationService",
    "PlatformApplicationService",
    "ProjectCard",
    "ProjectReadModelProjectionPort",
    "ProjectReadModelRefreshApplicationService",
    "ProjectScopeResolutionApplicationService",
    "ProjectStateLoaderApplicationService",
    "ProjectStateHydrationPort",
    "ProjectWorkspaceResponse",
    "ProjectWorkspaceApplicationService",
    "AgentQueryReadPort",
    "TopLevelContentReadPort",
    "QueryToolApplicationService",
    "ReadinessApplicationService",
    "ReadinessCheck",
    "ReadinessProbe",
    "ReadinessReport",
    "ReadModelSummaryService",
    "RateLimitCommand",
    "RateLimitDecision",
    "RequestRateLimitApplicationService",
    "RequestRateLimitPort",
    "EventPayload",
    "EventOutboxPort",
    "EventStreamBufferPort",
    "PlatformEventEntityReaderPort",
    "PlatformEventStreamPort",
    "ToolDefinition",
    "ToolApprovalVerifierApplicationService",
    "ToolApprovalVerificationStatePort",
    "ToolInvocationAuthorizationApplicationService",
    "ToolInvocation",
    "ToolInvocationApplicationService",
    "ToolInvocationProjectionApplicationService",
    "ToolInvocationProjectionStatePort",
    "ToolInvocationEventProjectionPort",
    "ToolInvocationRequest",
    "ToolResult",
    "TopLevelContentApplicationService",
    "UserAvatarUpdateRequest",
    "UserProfile",
    "VersionSummary",
    "WelcomeResponse",
    "core_tool_definitions",
    "system_image_tool_definitions",
]

_EXPORT_MODULES = {
    "AccountApplicationService": ".accounts",
    "AccountIdentityPort": ".account_ports",
    "AuthLoginRequest": ".account_models",
    "AuthRegisterRequest": ".account_models",
    "AuthSessionResponse": ".account_models",
    "AuditEvent": ".tool_models",
    "AuditEventPersistencePort": ".projection_ports",
    "AuthServiceError": ".auth_service",
    "AuthSessionResult": ".auth_service",
    "AvatarImageContent": ".auth_service",
    "BuildResponse": ".read_models",
    "CurrentUserProviderPort": ".account_ports",
    "DashboardResponse": ".read_models",
    "DemoSeedApplicationService": ".demo_seed",
    "DemoSeedBaseline": ".demo_seed_ports",
    "DemoSeedSystemImage": ".demo_seed_ports",
    "DemoSeedWorkspacePort": ".demo_seed_ports",
    "DocumentationEntry": ".read_models",
    "product_documentation_entries": ".documentation_catalog",
    "GovernanceApplicationError": ".governance",
    "GovernanceApplicationService": ".governance",
    "ModelConfigurationApplicationService": ".model_configurations",
    "ModelConfigurationGatewayPort": ".model_configuration_ports",
    "ModelConfigurationRepositoryPort": ".model_configuration_ports",
    "ModelConfigurationSecretPort": ".model_configuration_ports",
    "ModelConfigurationStatePort": ".model_configuration_ports",
    "ModelConfigurationTestGrantPort": ".model_configuration_ports",
    "OperationalMetricsExportPort": ".operational_metrics",
    "PlatformApplicationError": ".errors",
    "PlatformAuditApplicationService": ".audit_events",
    "PlatformEventApplicationService": ".events",
    "PlatformEventStreamApplicationService": ".event_streams",
    "PlatformApplicationService": ".use_cases",
    "ProjectCard": ".project_models",
    "ProjectReadModelProjectionPort": ".read_model_ports",
    "ProjectReadModelRefreshApplicationService": ".read_model_refresh",
    "ProjectScopeResolutionApplicationService": ".scope_resolution",
    "ProjectStateLoaderApplicationService": ".project_state_loader",
    "ProjectStateHydrationPort": ".state_hydration_ports",
    "ProjectWorkspaceResponse": ".read_models",
    "ProjectWorkspaceApplicationService": ".project_workspace",
    "AgentQueryReadPort": ".read_query_ports",
    "TopLevelContentReadPort": ".read_query_ports",
    "QueryToolApplicationService": ".query_tools",
    "ReadinessApplicationService": ".readiness",
    "ReadinessCheck": ".readiness",
    "ReadinessProbe": ".readiness",
    "ReadinessReport": ".readiness",
    "ReadModelSummaryService": ".read_models",
    "RateLimitCommand": ".request_rate_limits",
    "RateLimitDecision": ".request_rate_limits",
    "RequestRateLimitApplicationService": ".request_rate_limits",
    "RequestRateLimitPort": ".request_rate_limits",
    "EventPayload": ".tool_models",
    "EventOutboxPort": ".event_ports",
    "EventStreamBufferPort": ".event_ports",
    "PlatformEventEntityReaderPort": ".event_ports",
    "PlatformEventStreamPort": ".event_ports",
    "ToolDefinition": ".tool_models",
    "ToolApprovalVerifierApplicationService": ".approval_verifier",
    "ToolApprovalVerificationStatePort": ".approval_ports",
    "ToolInvocation": ".tool_models",
    "ToolInvocationApplicationService": ".tool_invocations",
    "ToolInvocationAccessPort": ".tool_invocation_ports",
    "ToolInvocationApplicationStatePort": ".tool_invocation_ports",
    "ToolInvocationExecutionPort": ".tool_invocation_ports",
    "ToolStatusEventPort": ".tool_invocation_ports",
    "ToolInvocationAuthorizationApplicationService": ".tool_authorization",
    "ToolInvocationProjectionApplicationService": ".tool_projection",
    "ToolInvocationProjectionStatePort": ".projection_ports",
    "ToolInvocationEventProjectionPort": ".event_ports",
    "ToolInvocationRequest": ".tool_models",
    "ToolResult": ".tool_models",
    "TopLevelContentApplicationService": ".top_level_content",
    "UserAvatarUpdateRequest": ".account_models",
    "UserProfile": ".account_models",
    "VersionSummary": ".project_models",
    "WelcomeResponse": ".read_models",
    "core_tool_definitions": ".tool_catalog",
    "system_image_tool_definitions": ".tool_catalog",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
