from __future__ import annotations

from .tool_models import ToolDefinition


def core_tool_definitions() -> list[ToolDefinition]:
    return [
        ToolDefinition(
            tool_id="project.create",
            label="Create Project",
            tool_kind="project",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Create a project draft and prepare system image initialization.",
            required_context=["project_name"],
            produced_objects=["Project", "ConversationSession"],
        ),
        ToolDefinition(
            tool_id="project.assets.connect",
            label="Connect Project Assets",
            tool_kind="project",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Connect project sources and delegate source binding to the system image source registry.",
            required_context=["project_id", "source_specs"],
            produced_objects=["RawAssetRecord", "Project"],
        ),
        ToolDefinition(
            tool_id="project.status.get",
            label="Get Project Status",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return project onboarding, system image, and quality-loop status through the tool path.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="version.create",
            label="Create Version",
            tool_kind="version",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Fork a working version branch from the current project baseline.",
            required_context=["project_id", "version_name"],
            produced_objects=["Version"],
        ),
        ToolDefinition(
            tool_id="version.inputs.import",
            label="Import Version Inputs",
            tool_kind="version",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Import version-level US work items and attach them to the active version branch.",
            required_context=["project_id", "version_id", "us_items"],
            produced_objects=["USWorkItem", "Version"],
        ),
        ToolDefinition(
            tool_id="version.branch.bind",
            label="Bind Development Branch",
            tool_kind="version",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Bind a Git branch or change scope to the active version.",
            required_context=["project_id", "version_id", "branch_name"],
            produced_objects=["Version"],
        ),
        ToolDefinition(
            tool_id="version.participants.assign",
            label="Assign Version Participants",
            tool_kind="version",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Assign version participants and US owners without bypassing the tool invocation audit chain.",
            required_context=["project_id", "version_id", "assignments"],
            produced_objects=["Version", "USWorkItem"],
        ),
        ToolDefinition(
            tool_id="version.risk.initialize",
            label="Initialize Version Risk",
            tool_kind="version",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Initialize the version quality risk view from US, system image, and execution state.",
            required_context=["project_id", "version_id"],
            produced_objects=["Version", "ReleaseReadiness"],
        ),
        ToolDefinition(
            tool_id="version.progress.get",
            label="Get Version Progress",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return version progress, remaining work, and risk summary through the tool path.",
            required_context=["project_id", "version_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="us.task.start",
            label="Start US Quality Task",
            tool_kind="us",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Start a US quality loop and prepare task context, asset lanes, and next recommended tools.",
            required_context=["project_id", "us_id"],
            produced_objects=["TaskContext", "QualityAssetPack", "USWorkItem"],
        ),
        ToolDefinition(
            tool_id="quality.scope.generate",
            label="Generate Test Scope",
            tool_kind="analysis",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Generate the testing scope from system image context, US inputs, and historical test evidence.",
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "QualityProfile"],
        ),
        ToolDefinition(
            tool_id="quality.scenario.generate",
            label="Generate Scenarios",
            tool_kind="analysis",
            scope="either",
            risk_level="low",
            confirmation_mode="none",
            description="Generate structured test scenarios for the selected US.",
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "AgentGoal"],
        ),
        ToolDefinition(
            tool_id="quality.plan.generate",
            label="Generate Verification Plan",
            tool_kind="analysis",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description=(
                "Generate priorities, environment and data requirements, execution allocation, "
                "performance checks, and approval points from approved scenarios."
            ),
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "VerificationPlan"],
        ),
        ToolDefinition(
            tool_id="quality.case.generate",
            label="Generate Test Cases",
            tool_kind="analysis",
            scope="either",
            risk_level="low",
            confirmation_mode="none",
            description="Generate structured test cases from approved scenario coverage.",
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "TestCaseSet"],
        ),
        ToolDefinition(
            tool_id="quality.asset-pack.refresh",
            label="Refresh Quality Asset Pack",
            tool_kind="analysis",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Refresh the QualityAssetPack revision chain and summarize current quality assets.",
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack"],
        ),
        ToolDefinition(
            tool_id="automation.generate",
            label="Generate Automation",
            tool_kind="analysis",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description=(
                "Generate a versioned, reviewable Playwright automation blueprint from "
                "approved cases without starting execution."
            ),
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "AutomationAsset"],
        ),
        ToolDefinition(
            tool_id="quality.change-doc.generate",
            label="Generate Quality Change Document",
            tool_kind="analysis",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description=(
                "Generate a traceable change record from the US, code and system-image deltas, "
                "quality assets, risks, and execution evidence."
            ),
            required_context=["project_id", "us_id"],
            produced_objects=["QualityAssetPack", "QualityChangeDocument"],
        ),
        ToolDefinition(
            tool_id="us.status.get",
            label="Get US Quality Status",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return persisted quality-loop progress, evidence, and next actions for one US.",
            required_context=["project_id", "us_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="run.start",
            label="Start Run",
            tool_kind="execution",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description=(
                "Execute a selected script from the current versioned automation asset "
                "through the RunOrchestrator lifecycle boundary."
            ),
            required_context=["project_id", "us_id", "base_url"],
            produced_objects=["Run", "ExecutionEvidence"],
        ),
        ToolDefinition(
            tool_id="run.progress.get",
            label="Get Run Progress",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return execution run status, evidence, and failure next steps through the tool path.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="run.retry",
            label="Retry Run",
            tool_kind="execution",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description=(
                "Retry a prior Run using its persisted target, automation revision, script, and validated "
                "execution plan; client-provided steps are never accepted."
            ),
            required_context=["project_id", "run_id"],
            produced_objects=["Run", "ExecutionEvidence"],
        ),
        ToolDefinition(
            tool_id="failure.analyze",
            label="Analyze Failure",
            tool_kind="analysis",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Analyze a failed run and materialize a structured FailureReport with evidence references.",
            required_context=["project_id", "run_id"],
            produced_objects=["FailureReport", "ExecutionEvidence"],
        ),
        ToolDefinition(
            tool_id="release.advice.get",
            label="Get Release Advice",
            tool_kind="governance",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return release readiness advice without creating the formal ReleaseDecision.",
            required_context=["project_id", "us_id"],
            produced_objects=["ReleaseReadiness"],
        ),
        ToolDefinition(
            tool_id="healing.propose",
            label="Propose Healing",
            tool_kind="analysis",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Propose a bounded healing action for a FailureReport; repeated fingerprints fall back to human review.",
            required_context=["project_id", "run_id"],
            produced_objects=["FailureReport", "AgentDecision"],
        ),
        ToolDefinition(
            tool_id="release.assess",
            label="Assess Release Readiness",
            tool_kind="governance",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Assess release readiness from quality assets, automation evidence, and governance state.",
            required_context=["project_id", "us_id"],
            produced_objects=["ReleaseReadiness", "QualityProfile"],
        ),
        ToolDefinition(
            tool_id="approval.request",
            label="Request Approval",
            tool_kind="governance",
            scope="central",
            risk_level="high",
            confirmation_mode="user_confirm",
            description="Create a governance approval request for release decision, merge, or baseline promotion.",
            required_context=["project_id", "purpose"],
            produced_objects=["ApprovalRecord", "AuditEvent"],
        ),
        ToolDefinition(
            tool_id="approval.decide",
            label="Decide Approval",
            tool_kind="governance",
            scope="central",
            risk_level="high",
            confirmation_mode="user_confirm",
            description="Record an explicit approval or rejection decision for a governance approval request.",
            required_context=["project_id", "approval_id", "decision"],
            produced_objects=["ApprovalRecord", "AuditEvent"],
        ),
        ToolDefinition(
            tool_id="release.decision.submit",
            label="Submit Release Decision",
            tool_kind="governance",
            scope="central",
            risk_level="high",
            confirmation_mode="approval_required",
            description="Submit the formal ReleaseDecision after release readiness has been assessed and approved.",
            required_context=["project_id", "approval_id"],
            produced_objects=["ReleaseDecision", "AuditEvent"],
        ),
        ToolDefinition(
            tool_id="resolution.merge",
            label="Merge Resolution",
            tool_kind="governance",
            scope="central",
            risk_level="high",
            confirmation_mode="user_confirm",
            description="Run a governed three-way merge and persist every unresolved field-level conflict.",
            required_context=["project_id", "target_ref", "base", "left", "right"],
            produced_objects=["MergedResolution", "AuditEvent"],
        ),
        ToolDefinition(
            tool_id="baseline.promote",
            label="Promote Baseline",
            tool_kind="governance",
            scope="central",
            risk_level="critical",
            confirmation_mode="approval_required",
            description="Promote or write back the official system image baseline from an approved release decision.",
            required_context=["project_id", "approval_id"],
            produced_objects=["Baseline", "AuditEvent"],
        ),
        ToolDefinition(
            tool_id="query.answer",
            label="Answer Conversation Query",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Answer a conversational request through the canonical ToolInvocation path.",
            required_context=["conversation_id", "user_message"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.dashboard.progress",
            label="Check Portfolio Progress",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize overall project, version, execution, and approval progress from the dashboard.",
            required_context=[],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.project.status",
            label="Check Project Status",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize project health, active version, and system image readiness.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.version.status",
            label="Check Version Status",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize version closure, blockers, and remaining quality work.",
            required_context=["project_id", "version_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.workspace.status",
            label="Check Workspace Status",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize the current US workspace, asset lanes, and the best next action.",
            required_context=["project_id", "us_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.governance.status",
            label="Check Governance Queue",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize approvals, merge pressure, and release blockers.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="progress.get",
            label="Get Progress",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return current portfolio, project, or workspace progress using the canonical query tool path.",
            required_context=[],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="risk.summary.get",
            label="Get Risk Summary",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return current version and project risk signals through the canonical query tool path.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="system-image.inspect",
            label="Inspect System Image",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Inspect system image objects, relationships, source freshness, and quality context.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="conflicts.get",
            label="Get Conflicts",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Return unresolved governance, release, and pending_merge conflicts through the tool path.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.knowledge.status",
            label="Check Knowledge State",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize the system image branch state and knowledge hotspots for a project.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
        ToolDefinition(
            tool_id="query.system_image.status",
            label="Check System Image",
            tool_kind="query",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description="Summarize source freshness, baseline readiness, relationships, and quality metric snapshots.",
            required_context=["project_id"],
            produced_objects=["ConversationSession"],
        ),
    ]


def system_image_tool_definitions() -> list[ToolDefinition]:
    return [
        ToolDefinition(
            tool_id="system_image.sources.register",
            label="Register System Image Sources",
            tool_kind="project",
            scope="central",
            risk_level="low",
            confirmation_mode="none",
            description=(
                "Register the first-class source groups used to build a project system image. "
                "Input may include source_specs: [{source_type: code|us_doc|test_asset, source_uri: file path or external URI}]."
            ),
            required_context=["project_id"],
            produced_objects=["RawAssetRecord"],
            input_schema_ref="schema://system-image/sources-register-input",
            output_schema_ref="schema://system-image/sources-register-output",
        ),
        ToolDefinition(
            tool_id="system_image.sources.ingest",
            label="Ingest System Image Sources",
            tool_kind="sync",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description=(
                "Index the required code source and any registered optional historical US "
                "documents or tests into raw system image assets."
            ),
            required_context=["project_id"],
            produced_objects=["RawAssetRecord", "ExecutionEvidence"],
            input_schema_ref="schema://system-image/sources-ingest-input",
            output_schema_ref="schema://system-image/sources-ingest-output",
        ),
        ToolDefinition(
            tool_id="system_image.context.materialize",
            label="Materialize System Context",
            tool_kind="analysis",
            scope="central",
            risk_level="medium",
            confirmation_mode="none",
            description="Materialize context objects, relationships, and quality metric snapshots from indexed sources.",
            required_context=["project_id"],
            produced_objects=["ContextObject", "ContextRelationship", "QualityMetricSnapshot"],
            input_schema_ref="schema://system-image/context-materialize-input",
            output_schema_ref="schema://system-image/context-materialize-output",
        ),
        ToolDefinition(
            tool_id="system_image.baseline.initialize",
            label="Initialize Official System Image",
            tool_kind="governance",
            scope="central",
            risk_level="high",
            confirmation_mode="user_confirm",
            description="Promote materialized context into the first Official System Image baseline.",
            required_context=["project_id"],
            produced_objects=["Baseline", "AuditEvent"],
            input_schema_ref="schema://system-image/baseline-initialize-input",
            output_schema_ref="schema://system-image/baseline-initialize-output",
        ),
    ]
