#!/usr/bin/env bash

# Shared local runtime for API, Temporal worker, and Playwright runner.
# This file must be sourced so every host process receives identical secrets
# and durable-runtime settings.

if [[ -n "${BASH_VERSION:-}" ]]; then
  NASUS_DEV_RUNTIME_ENV_SOURCE="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  NASUS_DEV_RUNTIME_ENV_SOURCE="${(%):-%N}"
else
  NASUS_DEV_RUNTIME_ENV_SOURCE="$0"
fi

NASUS_DEV_ROOT="$(cd "$(dirname "$NASUS_DEV_RUNTIME_ENV_SOURCE")/.." && pwd)"
unset NASUS_DEV_RUNTIME_ENV_SOURCE

if [[ -f "$NASUS_DEV_ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$NASUS_DEV_ROOT/.env"
  set +a
fi

export POSTGRES_DB="${POSTGRES_DB:-nasus}"
export POSTGRES_USER="${POSTGRES_USER:-nasus}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-nasus_dev_password}"
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"

export MINIO_ROOT_USER="${MINIO_ROOT_USER:-nasus}"
export MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-nasus_dev_password}"
export MINIO_API_PORT="${MINIO_API_PORT:-9000}"
export MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9001}"
export NASUS_S3_BUCKET="${NASUS_S3_BUCKET:-nasus-artifacts}"

export NASUS_ENV="${NASUS_ENV:-local}"
export NASUS_DATABASE_URL="${NASUS_DATABASE_URL:-postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}}"
export NASUS_AUTO_CREATE_TABLES=false
export NASUS_STATE_DIR="${NASUS_STATE_DIR:-$NASUS_DEV_ROOT/.nasus/state}"
export NASUS_SEED_DEMO_DATA=false

export NASUS_S3_ENDPOINT="${NASUS_S3_ENDPOINT:-http://127.0.0.1:${MINIO_API_PORT}}"
export NASUS_S3_ACCESS_KEY="${NASUS_S3_ACCESS_KEY:-$MINIO_ROOT_USER}"
export NASUS_S3_SECRET_KEY="${NASUS_S3_SECRET_KEY:-$MINIO_ROOT_PASSWORD}"
export NASUS_S3_REGION="${NASUS_S3_REGION:-us-east-1}"
export NASUS_SOURCE_CACHE_DIR="${NASUS_SOURCE_CACHE_DIR:-$NASUS_DEV_ROOT/.nasus/source-cache}"
export NASUS_GIT_ALLOWED_HOSTS="${NASUS_GIT_ALLOWED_HOSTS:-github.com,gitlab.com,bitbucket.org}"
export NASUS_GIT_ALLOWED_SCHEMES="${NASUS_GIT_ALLOWED_SCHEMES:-https,ssh,git}"
export NASUS_CODE_GRAPH_MODE="${NASUS_CODE_GRAPH_MODE:-optional}"
export NASUS_CODE_GRAPH_BINARY="${NASUS_CODE_GRAPH_BINARY:-$NASUS_DEV_ROOT/.venv/bin/codebase-memory-mcp}"
export NASUS_CODE_GRAPH_INDEX_MODE="${NASUS_CODE_GRAPH_INDEX_MODE:-moderate}"
export NASUS_CODE_GRAPH_CACHE_DIR="${NASUS_CODE_GRAPH_CACHE_DIR:-${NASUS_STATE_DIR:-.nasus}/code-graph-cache}"
export NASUS_SOURCE_ALLOWED_LOCAL_ROOTS="${NASUS_SOURCE_ALLOWED_LOCAL_ROOTS:-$NASUS_DEV_ROOT}"

export NASUS_AUTH_MODE="${NASUS_AUTH_MODE:-dev}"
export NASUS_CORS_ALLOW_ORIGINS="${NASUS_CORS_ALLOW_ORIGINS:-http://127.0.0.1:5173,http://localhost:5173}"
export NASUS_RATE_LIMIT_ENABLED="${NASUS_RATE_LIMIT_ENABLED:-false}"
export NASUS_RATE_LIMIT_BACKEND="${NASUS_RATE_LIMIT_BACKEND:-postgres}"
export NASUS_RATE_LIMIT_WINDOW_SECONDS="${NASUS_RATE_LIMIT_WINDOW_SECONDS:-60}"
export NASUS_RATE_LIMIT_AUTH_PER_WINDOW="${NASUS_RATE_LIMIT_AUTH_PER_WINDOW:-10}"
export NASUS_RATE_LIMIT_AGENT_PER_WINDOW="${NASUS_RATE_LIMIT_AGENT_PER_WINDOW:-30}"
export NASUS_RATE_LIMIT_API_PER_WINDOW="${NASUS_RATE_LIMIT_API_PER_WINDOW:-120}"

if [[ -z "${NASUS_SETTINGS_ENCRYPTION_SECRET:-}" ]]; then
  settings_key_file="$NASUS_STATE_DIR/settings.key"
  if [[ -f "$settings_key_file" ]]; then
    NASUS_SETTINGS_ENCRYPTION_SECRET="$(<"$settings_key_file")"
  else
    NASUS_SETTINGS_ENCRYPTION_SECRET="nasus-local-shared-settings-secret-change-me"
  fi
fi
export NASUS_SETTINGS_ENCRYPTION_SECRET

# The integrated development command intentionally runs the production-grade
# orchestration adapters. Override only through the explicit NASUS_DEV_* knobs.
export NASUS_AGENT_WORKFLOW_RUNTIME="${NASUS_DEV_AGENT_WORKFLOW_RUNTIME:-temporal}"
export NASUS_AGENT_GRAPH_RUNTIME="${NASUS_DEV_AGENT_GRAPH_RUNTIME:-langgraph}"
export NASUS_LANGGRAPH_CHECKPOINT_BACKEND="${NASUS_DEV_LANGGRAPH_CHECKPOINT_BACKEND:-postgres}"
export NASUS_LANGGRAPH_AGENT_LOOP_GRAPH="${NASUS_LANGGRAPH_AGENT_LOOP_GRAPH:-nasus-agent-loop}"
export NASUS_TEMPORAL_ADDRESS="${NASUS_TEMPORAL_ADDRESS:-127.0.0.1:7233}"
export NASUS_TEMPORAL_NAMESPACE="${NASUS_TEMPORAL_NAMESPACE:-default}"
export NASUS_TEMPORAL_TASK_QUEUE="${NASUS_TEMPORAL_TASK_QUEUE:-nasus-agent-goals}"
export NASUS_TEMPORAL_AGENT_GOAL_WORKFLOW="${NASUS_TEMPORAL_AGENT_GOAL_WORKFLOW:-NasusAgentGoalWorkflow}"
export NASUS_TEMPORAL_CURRENT_GOAL_QUERY="${NASUS_TEMPORAL_CURRENT_GOAL_QUERY:-current_goal}"
export NASUS_TEMPORAL_RESUME_SIGNAL="${NASUS_TEMPORAL_RESUME_SIGNAL:-resume_goal}"
export NASUS_TEMPORAL_QUERY_TIMEOUT_SECONDS="${NASUS_TEMPORAL_QUERY_TIMEOUT_SECONDS:-60}"
export NASUS_TEMPORAL_QUERY_POLL_INTERVAL_SECONDS="${NASUS_TEMPORAL_QUERY_POLL_INTERVAL_SECONDS:-0.1}"

export NASUS_RUNNER_MODE="${NASUS_DEV_RUNNER_MODE:-http}"
export NASUS_RUNNER_PORT="${NASUS_RUNNER_PORT:-8090}"
export NASUS_RUNNER_ENDPOINT="${NASUS_RUNNER_ENDPOINT:-http://127.0.0.1:${NASUS_RUNNER_PORT}}"
export NASUS_RUNNER_SERVICE_TOKEN="${NASUS_RUNNER_SERVICE_TOKEN:-nasus-local-runner-service-token-1234567890}"
export NASUS_RUNNER_ALLOWED_HOSTS="${NASUS_RUNNER_ALLOWED_HOSTS:-localhost,127.0.0.1}"
export NASUS_RUNNER_REQUEST_TIMEOUT_SECONDS="${NASUS_RUNNER_REQUEST_TIMEOUT_SECONDS:-130}"

export NASUS_API_PORT="${NASUS_API_PORT:-8000}"
export NASUS_PORTAL_PORT="${NASUS_PORTAL_PORT:-5173}"
export TEMPORAL_PORT="${TEMPORAL_PORT:-7233}"
export TEMPORAL_UI_PORT="${TEMPORAL_UI_PORT:-8088}"
export NASUS_DEV_RUNTIME_DIR="${NASUS_DEV_RUNTIME_DIR:-$NASUS_DEV_ROOT/.nasus/dev}"
